# Generated by Django 6.0.1 on 2026-01-11 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateTimeField()),
                ('finalizada', models.BooleanField(default=False)),
                ('requiere_evaluacion', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TareaGrupal',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tarea')),
                ('alumnos', models.ManyToManyField(related_name='tareas_grupales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.tarea',),
        ),
        migrations.CreateModel(
            name='TareaIndividual',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tarea')),
                ('alumno_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.tarea',),
        ),
    ]
